# Generated by Django 5.0.4 on 2024-04-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_alter_amenity_options_alter_facility_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="house_rule",
            new_name="house_rules",
        ),
    ]
