# Generated by Django 5.0.4 on 2024-04-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0008_alter_photo_room_alter_room_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.ImageField(upload_to="room_photos"),
        ),
    ]
