# Generated by Django 5.0.4 on 2024-04-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reivew",
            name="accuracy",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reivew",
            name="check_in",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reivew",
            name="clearnliness",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reivew",
            name="communication",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reivew",
            name="location",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reivew",
            name="value",
            field=models.IntegerField(),
        ),
    ]
