# Generated by Django 5.1a1 on 2024-06-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_rename_reivew_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="clearnliness",
            new_name="cleanliness",
        ),
    ]
